import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Buyzaar",
  description: "Generated by create next app",
};

export default async function ProfileLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <section className="bg-gray-100">{children}</section>;
}
