import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/rootLayout/Navbar";
import Footer from "@/components/rootLayout/Footer";
import { CartProvider } from "@/utils/CartContext";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Buyzaar",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("access_token")?.value;

  let isLoggedIn = false;

  if (accessToken) {
    try {
      const res = await fetch("http://localhost:5000/auth/profile", {
        headers: {
          Cookie: `access_token=${accessToken}`,
        },
        cache: "no-store", // Zapobiega cachaowaniu odpowiedzi
      });
      console.log(res);
      isLoggedIn = res.status >= 200 && res.status < 300;
    } catch (error) {
      console.error("Error verifying authentication:", error);
      // W przypadku błędu, zachowujemy isLoggedIn jako false
    }
  }
  //TODO fix this: this res gets unauthorised error
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <Navbar isLoggedIn={isLoggedIn} />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
